// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Company struct {
	ID          string              `json:"id"`
	Owner       *CompanyOwner       `json:"owner"`
	Information *CompanyInformation `json:"information"`
	Franchises  []*Franchise        `json:"franchises"`
}

type CompanyInformation struct {
	Name      string    `json:"name"`
	TaxNumber string    `json:"tax_number"`
	Location  *Location `json:"location"`
}

type CompanyOwner struct {
	ID        string               `json:"id"`
	Name      string               `json:"name"`
	FirstName string               `json:"firstName"`
	LastName  string               `json:"lastName"`
	Contact   *CompanyOwnerContact `json:"contact"`
}

type CompanyOwnerContact struct {
	Email    string    `json:"email"`
	Phone    string    `json:"phone"`
	Location *Location `json:"location"`
}

type CreateFranchiseInput struct {
	URL string `json:"url"`
}

type CreatedFranchise struct {
	ID  string `json:"id"`
	URL string `json:"url"`
}

type FindFranchisesCriteria struct {
	Name *string `json:"name,omitempty"`
}

type Franchise struct {
	ID       string    `json:"id"`
	Title    string    `json:"title"`
	SiteName string    `json:"siteName"`
	URL      string    `json:"url"`
	Location *Location `json:"location"`
}

type Location struct {
	ZipCode string `json:"zip_code"`
	Adress  string `json:"adress"`
	City    string `json:"city"`
	Country string `json:"country"`
}

type Mutation struct {
}

type Query struct {
}

type UpdateFranchiseInput struct {
	ID      string  `json:"id"`
	URL     *string `json:"url,omitempty"`
	Name    *string `json:"name,omitempty"`
	Company *string `json:"company,omitempty"`
}
